#MYSQL connecion details

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
     

#ORM details

  jpa:
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
       ddl-auto: create
    show-sql: true


